blank_issues_enabled: false
contact_links:
  - name: PyTorch-OOD documentation
    url: https://pytorch-ood.readthedocs.io/en/latest/
    about: Check the documentation before opening a support request.
